reorder_modules = false

ignore = [
    # Mostly third-party code, copied into our tree (see corresponding LICENSE files for details)
    "crates/9p",
    "crates/framework/icecap-failure",
    "crates/framework/icecap-unwind",

    # TODO
    "crates/hypervisor/components",
    "crates/hypervisor/icecap-vmm",
]
