for f in ~/.bash_completion.d/*; do
  . $f
done

__icecap_default_expression=${__icecap_default_expression:-.}

alias n="nix-build ${__icecap_default_expression} -A"
alias nn="nix-build --no-out-link ${__icecap_default_expression} -A"
alias ne="nix-instantiate --eval ${__icecap_default_expression} -A"
alias nes="nix-instantiate --eval --strict ${__icecap_default_expression} -A"

alias ns='nix-shell'

alias r="./result/run"
alias b='./result/debug/icecap-show-backtrace'

complete -F _complete_alias n
complete -F _complete_alias nn
complete -F _complete_alias ne
complete -F _complete_alias nes
